import type { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Modern Wireless Headphones',
    description: 'Experience immersive sound with these sleek wireless headphones. Long battery life and comfortable design.',
    price: 129.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'headphones audio',
    category: 'Electronics',
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft and breathable, this t-shirt is made from 100% organic cotton. Perfect for everyday wear.',
    price: 24.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'shirt clothing',
    category: 'Apparel',
  },
  {
    id: '3',
    name: 'Smart Fitness Tracker',
    description: 'Monitor your activity, sleep, and heart rate with this advanced fitness tracker. Syncs with your smartphone.',
    price: 79.50,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wearable tech',
    category: 'Electronics',
  },
  {
    id: '4',
    name: 'Stainless Steel Water Bottle',
    description: 'Stay hydrated with this durable and eco-friendly water bottle. Keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 30.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'bottle drinkware',
    category: 'Home Goods',
  },
  {
    id: '5',
    name: 'Classic Leather Wallet',
    description: 'A timeless bifold wallet crafted from genuine leather. Features multiple card slots and a cash compartment.',
    price: 45.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wallet accessory',
    category: 'Accessories',
  },
  {
    id: '6',
    name: 'Gourmet Coffee Beans',
    description: 'Premium Arabica coffee beans, ethically sourced and roasted to perfection. Rich aroma and smooth flavor.',
    price: 18.75,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coffee food',
    category: 'Groceries',
  },
  {
    id: '7',
    name: 'Yoga Mat Extra Thick',
    description: 'High-density TPE yoga mat for superior comfort and support during your practice.',
    price: 35.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'yoga fitness',
    category: 'Sports',
  },
  {
    id: '8',
    name: 'Bluetooth Portable Speaker',
    description: 'Compact and powerful portable speaker with crisp sound and deep bass.',
    price: 59.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'speaker electronics',
    category: 'Electronics',
  },
];
